version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: time-tracking-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: time-tracking
    volumes:
      - mongodb_data:/data/db
    networks:
      - time-tracking-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: time-tracking-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/time-tracking
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-min-32-chars
      - JWT_EXPIRE=7d
    depends_on:
      - mongodb
    networks:
      - time-tracking-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: time-tracking-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - time-tracking-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  time-tracking-network:
    driver: bridge
